version: '3'

networks:
  frontend:
  backend:


services:

  photoprism:
    image: ${GCP_REPO_PATH}/photoprism
    container_name: photoprism
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      PHOTOPRISM_ADMIN_PASSWORD:
      PHOTOPRISM_DISABLE_SETTINGS: "true"
      PHOTOPRISM_DISABLE_TENSORFLOW: "true"
      PHOTOPRISM_PUBLIC: "true"
      PHOTOPRISM_DATABASE_DRIVER: mysql
      PHOTOPRISM_DATABASE_SERVER: mariadb
      PHOTOPRISM_DATABASE_PASSWORD: $MARIADB_PASSWORD
      PHOTOPRISM_SITE_URL: "https://${DOMAIN}/"
      PHOTOPRISM_SITE_DESCRIPTION: "It's a website. For a dog."
      PHOTOPRISM_SITE_CAPTION: "Larky"
      PHOTOPRISM_SITE_AUTHOR: "Kelly Gipson"
    user: "1000:1001"
    networks:
      - frontend
      - backend
    volumes:
      - "~/import:/photoprism/import"
      - "~/originals:/photoprism/originals"
      - "~/storage:/photoprism/storage"

  mariadb:
    image: mariadb:10.8
    container_name: mariadb
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    networks:
      - backend
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_ROOT_PASSWORD:
      MARIADB_DATABASE: photoprism
      MARIADB_USER: photoprism
      MARIADB_PASSWORD:
    volumes:
      - mariadb:/var/lib/mysql

  gateway:
    image: ${GCP_REPO_PATH}/swag
    container_name: swag
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      PUID: 1000
      PGID: 1001
      TZ: UTC
      URL: $DOMAIN
      VALIDATION: http
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
    volumes:
      - swag-data:/config

volumes:
  mariadb:
    driver: local
  swag-data:
    driver: local
