version: '3'

networks:
  frontend:
  backend:


services:

  photoprism:
    image: ${GCP_REPO_PATH}/photoprism
    container_name: photoprism
    restart: unless-stopped
    depends_on:
      - mariadb
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      PHOTOPRISM_ADMIN_PASSWORD:
      PHOTOPRISM_DISABLE_SETTINGS: "true"
      PHOTOPRISM_DISABLE_TENSORFLOW: "true"
      PHOTOPRISM_AUTH_MODE: "public"
      PHOTOPRISM_DATABASE_DRIVER: mysql
      PHOTOPRISM_DATABASE_SERVER: mariadb
      PHOTOPRISM_DATABASE_PASSWORD: photoprism
      PHOTOPRISM_SITE_URL: "https://${DOMAIN}/"
      PHOTOPRISM_SITE_DESCRIPTION: "It's a website. For a dog."
      PHOTOPRISM_SITE_CAPTION: "Larky"
      PHOTOPRISM_SITE_AUTHOR: "Kelly Gipson"
      PHOTOPRISM_SPONSOR: "true"
      PHOTOPRISM_IMPRINT: "Photos Copyright Kelly Gipson"
      PHOTOPRISM_SITE_TITLE: "Larky"
    user: "1000:1000"
    networks:
      - frontend
      - backend
    volumes:
      - photoprism-import:/photoprism/import
      - "~/data/photoprism/originals:/photoprism/originals"
      - "~/data/photoprism/storage:/photoprism/storage"

  mariadb:
    image: mariadb:10.9
    container_name: mariadb
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    networks:
      - backend
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: photoprism
      MARIADB_USER: photoprism
      MARIADB_PASSWORD: photoprism
    volumes:
      - "~/data/mariadb:/var/lib/mysql"

  gateway:
    image: lscr.io/linuxserver/swag
    container_name: swag
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
      URL: $DOMAIN
      VALIDATION: http
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
    volumes:
      - "~/data/swag:/config"

volumes:
  photoprism-import:
