UI:
  Scrollbar: true
  Zoom: false
  Theme: default
  Language: en
Templates:
  Default: index.tmpl
Maps:
  Animate: 0
  Style: streets
Features:
  Upload: false
  Download: true
  Private: false 
  Review: false
  Files: true
  Videos: true
  Folders: false
  Albums: false
  Moments: false
  Estimates: true
  People: true
  Labels: false
  Places: true
  Edit: false
  Archive: false
  Delete: false
  Share: true
  Library: false
  Import: true
  Logs: true
Import:
  Path: /
  Move: false
Index:
  Path: /
  Convert: true
  Rescan: false
Stack:
  UUID: true
  Meta: true
  Name: false
Share:
  Title: ""
Download:
  Name: file
